config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :expedients
  resources :bills
  resources :remissions
  resources :results
  resources :constancies
  resources :laboratories
  resources :phone_numbers
  resources :medic_patients
  resources :patients
  resources :medics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/constancy.rb
class Constancy < ApplicationRecord
end

app/models/expedient.rb
class Expedient < ApplicationRecord
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
end

app/models/medic.rb
class Medic < ApplicationRecord
	has_many :medic_patients
	has_many :patients, through: :medic_patients
end

app/models/medic_patient.rb
class MedicPatient < ApplicationRecord
  belongs_to :patient
  belongs_to :medic
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_one :expedient
	has_many :medic_patients
	has_many :medics, through: :medic_patients
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :patient
end

app/models/remission.rb
class Remission < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/remissions_controller.rb
class RemissionsController < ApplicationController
  before_action :set_remission, only: [:show, :edit, :update, :destroy]

  # GET /remissions
  # GET /remissions.json
  def index
    @remissions = Remission.all
  end

  # GET /remissions/1
  # GET /remissions/1.json
  def show
  end

  # GET /remissions/new
  def new
    @remission = Remission.new
  end

  # GET /remissions/1/edit
  def edit
  end

  # POST /remissions
  # POST /remissions.json
  def create
    @remission = Remission.new(remission_params)

    respond_to do |format|
      if @remission.save
        format.html { redirect_to @remission, notice: 'Remission was successfully created.' }
        format.json { render :show, status: :created, location: @remission }
      else
        format.html { render :new }
        format.json { render json: @remission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remissions/1
  # PATCH/PUT /remissions/1.json
  def update
    respond_to do |format|
      if @remission.update(remission_params)
        format.html { redirect_to @remission, notice: 'Remission was successfully updated.' }
        format.json { render :show, status: :ok, location: @remission }
      else
        format.html { render :edit }
        format.json { render json: @remission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remissions/1
  # DELETE /remissions/1.json
  def destroy
    @remission.destroy
    respond_to do |format|
      format.html { redirect_to remissions_url, notice: 'Remission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remission
      @remission = Remission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remission_params
      params.require(:remission).permit(:constancy_id, :laboratory_id, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/constancies_helper.rb
module ConstanciesHelper
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/remissions_helper.rb
module RemissionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/remissions/_form.html.erb
<%= form_for(remission) do |f| %>
  <% if remission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remission.errors.count, "error") %> prohibited this remission from being saved:</h2>

      <ul>
      <% remission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :constancy_id %>
    <%= f.number_field :constancy_id %>
  </div>

  <div class="field">
    <%= f.label :laboratory_id %>
    <%= f.number_field :laboratory_id %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/remissions/edit.html.erb
<h1>Editing Remission</h1>

<%= render 'form', remission: @remission %>

<%= link_to 'Show', @remission %> |
<%= link_to 'Back', remissions_path %>

app/views/remissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remisiones</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-xs-2">Constancias</th>
      <th class="col-xs-2">Laboratorio</th>
      <th class="col-xs-5">Fecha</th>
      <th class="col-xs-1">Acciones</th>
      <th class="col-xs-1"></th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @remissions.each do |remission| %>
      <tr>
        <td><%= remission.constancy_id %></td>
        <td><%= remission.laboratory_id %></td>
        <td><%= remission.date %></td>
        <td><%= link_to 'Mostrar', remission, class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Modificar', edit_remission_path(remission), class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Eliminar', remission, method: :delete, data: { confirm: 'Está Seguro?' }, class: 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Remision', new_remission_path, class: 'btn btn-default btn-sm' %>

app/views/remissions/new.html.erb
<h1>New Remission</h1>

<%= render 'form', remission: @remission %>

<%= link_to 'Back', remissions_path %>

app/views/remissions/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Remisiones</h1>

<div class = "field form-group">
  <strong>Constancia:</strong>
  <%= @remission.constancy_id %>
</div>

<div class = "field form-group">
  <%= @remission.laboratory_id %>
</div>

<div class = "field form-group">
  <strong>Fecha</strong>
  <%= @remission.date, class: "form-control" %>
</div>

<%= link_to 'Edit', edit_remission_path(@remission), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', remissions_path, class: 'btn btn-default btn-sm' %>