config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :expedients
  resources :bills
  resources :remissions
  resources :results
  resources :constancies
  resources :laboratories
  resources :phone_numbers
  resources :medic_patients
  resources :patients
  resources :medics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/constancy.rb
class Constancy < ApplicationRecord
end

app/models/expedient.rb
class Expedient < ApplicationRecord
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
end

app/models/medic.rb
class Medic < ApplicationRecord
	has_many :medic_patients
	has_many :patients, through: :medic_patients
end

app/models/medic_patient.rb
class MedicPatient < ApplicationRecord
  belongs_to :patient
  belongs_to :medic
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_one :expedient
	has_many :medic_patients
	has_many :medics, through: :medic_patients
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :patient
end

app/models/remission.rb
class Remission < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:constancy_id, :date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/constancies_helper.rb
module ConstanciesHelper
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/remissions_helper.rb
module RemissionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(result) do |f| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :constancy_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.number_field :constancy_id, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :date, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.date_select :date, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th class="col-xs-2">Constancy</th>
      <th class="col-xs-2">Date</th>
      <th class="col-xs-4">Description</th>
      <th class="col-xs-4">Acciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.constancy_id %></td>
        <td><%= result.date %></td>
        <td><%= result.description %></td>
        <td><%= link_to 'Show', result, class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Edit', edit_result_path(result), class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path, class: 'btn btn-default btn-sm' %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path, class: 'btn btn-default btn-sm' %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<div class="field form-group">
  <strong>Constancy:</strong>
  <%= @result.constancy_id %>
</div>

<div class="field form-group">
  <strong>Date:</strong>
  <%= @result.date %>
</div>

<div class="field form-group">
  <strong>Description:</strong>
  <%= @result.description %>
</div>

<%= link_to 'Edit', edit_result_path(@result), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', results_path, class: 'btn btn-default btn-sm' %>