config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :expedients
  resources :bills
  resources :remissions
  resources :results
  resources :constancies
  resources :laboratories
  resources :phone_numbers
  resources :medic_patients
  resources :patients
  resources :medics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/constancy.rb
class Constancy < ApplicationRecord
end

app/models/expedient.rb
class Expedient < ApplicationRecord
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
end

app/models/medic.rb
class Medic < ApplicationRecord
	has_many :medic_patients
	has_many :patients, through: :medic_patients
end

app/models/medic_patient.rb
class MedicPatient < ApplicationRecord
  belongs_to :patient
  belongs_to :medic
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_one :expedient
	has_many :medic_patients
	has_many :medics, through: :medic_patients
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :patient
end

app/models/remission.rb
class Remission < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:date, :subtotal, :tax, :discount, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/constancies_helper.rb
module ConstanciesHelper
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/remissions_helper.rb
module RemissionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.date_select :date, {date_separator: "</div><div class='col-sm-3'>"}, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :SubTotal, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :subtotal, class: 'form-control' %>
    </div>
  </div>
  <br>
  <div class="field">
    <%= f.label :Impuesto, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :tax, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :Descuento, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :discount, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :Total, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :total, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-default btn-sm' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-xs-3">Date</th>
      <th class="col-xs-2">Subtotal</th>
      <th class="col-xs-2">Tax</th>
      <th class="col-xs-2">Discount</th>
      <th class="col-xs-3">Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.date %></td>
        <td><%= bill.subtotal %></td>
        <td><%= bill.tax %></td>
        <td><%= bill.discount %></td>
        <td><%= bill.total %></td>
        <td><%= link_to 'Show', bill, class: 'btn btn-default btn-sm'%></td>
        <td><%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path, class: 'btn btn-default btn-sm' %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path, class: 'btn btn-default btn-sm' %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<div class="field form-group">
  <strong>Date:</strong>
  <%= @bill.date %>
</div>

<div class="field form-group">
  <strong>Subtotal:</strong>
  <%= @bill.subtotal %>
</div>

<div class="field form-group">
  <strong>Tax:</strong>
  <%= @bill.tax %>
</div>

<div class="field form-group">
  <strong>Discount:</strong>
  <%= @bill.discount %>
</div>

<div class="field form-group">
  <strong>Total:</strong>
  <%= @bill.total %>
</div>

<%= link_to 'Edit', edit_bill_path(@bill), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', bills_path, class: 'btn btn-default btn-sm' %>