config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :expedients
  resources :bills
  resources :remissions
  resources :results
  resources :constancies
  resources :laboratories
  resources :phone_numbers
  resources :medic_patients
  resources :patients
  resources :medics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/constancy.rb
class Constancy < ApplicationRecord
end

app/models/expedient.rb
class Expedient < ApplicationRecord
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
end

app/models/medic.rb
class Medic < ApplicationRecord
	has_many :medic_patients
	has_many :patients, through: :medic_patients
end

app/models/medic_patient.rb
class MedicPatient < ApplicationRecord
  belongs_to :patient
  belongs_to :medic
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_one :expedient
	has_many :medic_patients
	has_many :medics, through: :medic_patients
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :patient
end

app/models/remission.rb
class Remission < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:patient_id, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/constancies_helper.rb
module ConstanciesHelper
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/remissions_helper.rb
module RemissionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_for(phone_number) do |f| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-10">
      <%= f.number_field :patient_id, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :phone_number, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-10">
    <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-default btn-sm' %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Numbers</h1>

<table>
  <thead>
    <tr>
      <th class="col-xs-5">Patient</th>
      <th class="col-xs-4">Phone number</th>
      <th class="col-xs-1">Acciones</th>
      <th class="col-xs-1"></th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.patient %></td>
        <td><%= phone_number.phone_number %></td>
        <td><%= link_to 'Show', phone_number, class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number), class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phone_number_path, class: 'btn btn-default btn-sm' %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Back', phone_numbers_path, class: 'btn btn-default btn-sm' %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="field form-group">
  <strong>Patient:</strong>
  <%= @phone_number.patient %>
</div>

<div class="field form-group">
  <strong>Phone number:</strong>
  <%= @phone_number.phone_number %>
</div>

<%= link_to 'Edit', edit_phone_number_path(@phone_number), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', phone_numbers_path, class: 'btn btn-default btn-sm' %>